### ISSUE TITLE
missing files in solution

### ISSUE THREAD

**Issue by NicolaDelfino** [EdiWang/UWP-CharacterMap#1]
github missing of the following files:
*.pfx (not a big deal)
/Core/AppSettings.cs

so I'm not able to compile. could you fix it?

**Comment by NicolaDelfino** [comment]
missing also:
Square44x44Logo.scale-125.png 
Square44x44Logo.scale-150.png

**Comment by EdiWang** [comment]
Thanks @NicolaDelfino, seems VS2015 is messing up this. Fixed in 7c3639a85eeea3c88bdbcfcf0a3c66347c2dd2ad

**Comment by EdiWang** [comment]
Closing #1
