### ISSUE TITLE
Add ability to set the default font that is selected when the app opens

### ISSUE THREAD

**Issue by colinkiama** [EdiWang/UWP-CharacterMap#13]
This would save so much time.

**Comment by EdiWang** [comment]
Hi @colinkiama 

If you go to settings, you will find the the option already there. 

![image](https://user-images.githubusercontent.com/3304703/30328893-4f17b0aa-9803-11e7-8b63-b6075802bd39.png)

Turn it on, select a font and click "Set As Default" you will see it pop up automatically next time when you start the App.

![image](https://user-images.githubusercontent.com/3304703/30328893-4f17b0aa-9803-11e7-8b63-b6075802bd39.png)

**Comment by colinkiama** [comment]
Oh wow. I can’t believe I didn’t notice that. Thank You!

Sent from Mail for Windows 10
