### ISSUE TITLE
Some improvement

### ISSUE THREAD

**Issue by nicolgit** [EdiWang/UWP-CharacterMap#3]
These are my feedback (it means if I have time I could also try to push these stuff on your project in next days (no guarantee, I'm very busy in this period:-)
- Remember selected filter (all fonts/symbols only)
- Remember selected font
- To have somewhere in settings the size of the grid
- To have somewhere in settings the width/height of the .png
- UI on W10M is very confusing

as you can imagine I use your app a lot for generating and choose icons for my apps:-)

thank you!

**Comment by EdiWang** [comment]
UI on Windows 10 Mobile devices are not currently in design scope. Because this App is targeting mainly desktop users, there's no point to use it on phones.

**Comment by NicolaDelfino** [comment]
Yes, probably it's correct. 

The only scenario I see is: I'm near a collegue talking about a new icon I found that I show on the phone to him and he say "hey this is cool, ok, I can use it in the app, what's the character code?" 

I could read the code to him, or send an email to him with the xaml... 

not lifesaving, but nice to have:-)

**Comment by EdiWang** [comment]
Update: UI on Windows 10 Mobile is done.

**Comment by EdiWang** [comment]
Update: Remember selected filter (all fonts/symbols only) is done.

**Comment by EdiWang** [comment]
close #3
