### ISSUE TITLE
Add support for supplementary characters

### ISSUE THREAD

**Issue by amtlib-dot-dll** [EdiWang/UWP-CharacterMap#5]
This app is great, but I cannot find any character higher than U+FFFF, for example, 🔞(U+1F51E). Looking forward to the support of emoji's. Thank you very much:smile:

**Comment by EdiWang** [comment]
This is not the scope of this App now. But thanks anyway! It's a great idea, I may plan it in future release.

**Comment by EdiWang** [comment]
The issue is fixed in today's release. Closing it now.
